/**
* This file contains code for directing subcommands of the Rubber
* Duck CLI.
*/
use structopt::StructOpt;

pub mod dataserver;
pub mod environment;

/// The primary command for the CLI 
/// 
/// This is the root executable generated by cargo run/build
#[derive(Debug, StructOpt)]
#[structopt(
    name = "rd",
    about = "Welcome to Rubber Duck! This CLI assists you in completing all your necessary tasks related to the Rubber Duck environment.")]
pub struct RD {
    #[structopt(subcommand)]
    pub cmd: Command
}

/// Enumeration the lists the different subcommands
/// of the root CLI.
#[derive(Debug, StructOpt)]
pub enum Command {

    /// For the rubber duck CLI
    Dataserver(dataserver::DataserverCLI),

    /// To configure the environment
    Environment(environment::EnvironmentCLI)
}
